### ISSUE TITLE
Provide instructions for Windows systems

### ISSUE THREAD

**Issue by matteosecli** [matteosecli/pdf2archive#6]
This doesn't mean that there is an *official* Windows support; prebuilt packages (with e.g. Cygwin, GS and Java) will not be provided (as I don't have a chance to test them, so it's pointless so ship something untested).

However, being GS and Java cross-platform, there should be in principle no obstacle in running `pdf2archive` in Windows (once one has a __Bash__ shell). Additionally, given that I've put up `pdf2archive` right because Linux is discriminated in the availability of free PDF/A-1B converting solutions, it would not be nice to "discriminate back" Windows.

---

### Possible solutions

* __For Windows 10 on__
  An option would be to use the WSL. Checks are needed.
* __For older versions__
  I think we need something like [Cygwin](https://www.cygwin.com). Users can be instructed to open a Cygwin terminal and run `pdf2archive` as you would do on Linux, or we can provide them with a `.bat` wrapper. Checks are needed.

### TODO

- [ ] Find someone willing to test on Windows, as I don't have a Windows box available (and I don't plan to have one).
- [ ] Test the solution with WSL on Windows 10.
- [ ] Test the solution with Cygwin, both with and without a `.bat`.
- [ ] Provide instructions for installing Ghostscript, Java and a WSL Linux distro (or Cygwin).
